name: "Test Action"

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run tests
        uses: joluizquierdo/github-action-rust-tes01@main
